#spring.application.name: demo

app.run.type: default


test:
 goods:
   1:
     goodsNo: "1"
     goodsName: "자동차"
   2:
     goodsNo: "2"
     goodsName: "사과"


spring:
  datasource:
    hostip: ${hostip}
    username: ${username}
    password: ${password}