#spring.application.name: demo

app.run.type: default


test:
 goods:
   1:
     goodsNo: "1"
     goodsName: "Product AAAA"
   2:
     goodsNo: "2"
     goodsName: "Product BBBA"


spring:
  datasource:
    hostip: ${hostip}
    username: ${username}
    password: ${password}